### ISSUE TITLE
problem in running demo-1.  How can i fix it ?

### ISSUE THREAD

**Issue by archernsy** [liux520/RealESRGAN_Deg_Pipeline#2]
/media/data4/liuyj/xjy/RealESRGAN_Deg_Pipeline/utils/utils_blur.py:468: RuntimeWarning: invalid value encountered in divide
  lambda x, y: cutoff * special.j1(cutoff * np.sqrt(
Traceback (most recent call last):
  File "/media/data4/liuyj/xjy/RealESRGAN_Deg_Pipeline/Deg_pipeline.py", line 541, in <module>
    gt, gt_usm, lq, kernel1, kernel2, sinc_kernel = deg_pipeline(gt_path, uint8=True, test=True)
  File "/media/data4/liuyj/anaconda3/envs/xiaojy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/data4/liuyj/anaconda3/envs/xiaojy/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/media/data4/liuyj/xjy/RealESRGAN_Deg_Pipeline/Deg_pipeline.py", line 130, in forward
    lq, gt_usm, kernel1, kernel2, sinc_kernel = self.forward_deg(img_gt)
  File "/media/data4/liuyj/anaconda3/envs/xiaojy/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/media/data4/liuyj/xjy/RealESRGAN_Deg_Pipeline/Deg_pipeline.py", line 111, in forward_deg
    noised_2 = self.noise_2(sampled_2)
  File "/media/data4/liuyj/xjy/RealESRGAN_Deg_Pipeline/Deg_pipeline.py", line 261, in noise_2
    img = random_add_poisson_noise_pt(
  File "/media/data4/liuyj/xjy/RealESRGAN_Deg_Pipeline/utils/utils_noise.py", line 114, in random_add_poisson_noise_pt
    noise = random_generate_poisson_noise_pt(img, scale_range, gray_prob)
  File "/media/data4/liuyj/xjy/RealESRGAN_Deg_Pipeline/utils/utils_noise.py", line 130, in random_generate_poisson_noise_pt
    return generate_poisson_noise_pt(img, scale, gray_noise)
  File "/media/data4/liuyj/xjy/RealESRGAN_Deg_Pipeline/utils/utils_noise.py", line 163, in generate_poisson_noise_pt
    noise_gray = noise_gray.expand(b, 3, h, w)
RuntimeError: expand(torch.cuda.FloatTensor{[1, 1, 1, 192, 1152]}, size=[1, 3, 192, 1152]): the number of sizes provided (4) must be greater or equal to the number of dimensions in the tensor (5)

**Comment by liux520** [comment]
Sorry for the wait. Since I cannot reproduce your issue, I provide a test script that you can use to further locate the problem. Looking forward to your further reply.

```
import numpy as np
import torch
from torchvision.transforms.functional import to_tensor, rgb_to_grayscale


def test_two_rgb2gray_methods(img):
    img_gray_pytorch = rgb_to_grayscale(img, num_output_channels=1)
    img_gray_simple = (torch.tensor([0.2989, 0.587, 0.114], dtype=img.dtype, device=img.device).reshape(3, 1, 1) * img).sum(1).unsqueeze(1)

    print(img_gray_pytorch.shape, img_gray_simple.shape)
    print(img_gray_pytorch.all() == img_gray_simple.all())


def test_expand_repeat(img):
    img = img[:, 0, ...].unsqueeze(1)
    b, c, h, w = img.shape
    noise_gray_repeat = img.repeat(1, 3, 1, 1)
    noise_gray_expand = img.expand(b, 3, h, w)

    print(noise_gray_repeat.shape, noise_gray_expand.shape)
    print(noise_gray_repeat.all() == noise_gray_expand.all())


def generate_poisson_noise_pt(img, scale=1.0, gray_noise=0):
    """Generate a batch of poisson noise (PyTorch version)
    Args:
        img (Tensor): Input image, shape (b, c, h, w), range [0, 1], float32.
        scale (float | Tensor): Noise scale. Number or Tensor with shape (b).
            Default: 1.0.
        gray_noise (float | Tensor): 0-1 number or Tensor with shape (b).
            0 for False, 1 for True. Default: 0.
    Returns:
        (Tensor): Returned noisy image, shape (b, c, h, w), range[0, 1],
            float32.
    """
    b, _, h, w = img.size()
    if isinstance(gray_noise, (float, int)):
        cal_gray_noise = gray_noise > 0
    else:
        gray_noise = gray_noise.view(b, 1, 1, 1)
        cal_gray_noise = torch.sum(gray_noise) > 0
    if cal_gray_noise:
        # rgb -> gray method-1: (from torchvision.transforms.functional import rgb_to_grayscale)
        # img_gray = rgb_to_grayscale(img, num_output_channels=1)

        # rgb -> gray method-2: (Since lower version of pytorch doesn't have rgb_to_grayscale function.)
        img_gray = (torch.tensor([0.2989, 0.587, 0.114], dtype=img.dtype, device=img.device).reshape(3, 1, 1) * img).sum(1)
        img_gray = torch.unsqueeze(img_gray, 1)

        # round and clip image for counting vals correctly
        img_gray = torch.clamp((img_gray * 255.0).round(), 0, 255) / 255.
        # use for-loop to get the unique values for each sample
        vals_list = [len(torch.unique(img_gray[i, :, :, :])) for i in range(b)]
        vals_list = [2 ** np.ceil(np.log2(vals)) for vals in vals_list]
        vals = img_gray.new_tensor(vals_list).view(b, 1, 1, 1)
        out = torch.poisson(img_gray * vals) / vals
        noise_gray = out - img_gray
        noise_gray = noise_gray.expand(b, 3, h, w)

    # always calculate color noise
    # round and clip image for counting vals correctly
    img = torch.clamp((img * 255.0).round(), 0, 255) / 255.
    # use for-loop to get the unique values for each sample
    vals_list = [len(torch.unique(img[i, :, :, :])) for i in range(b)]
    vals_list = [2 ** np.ceil(np.log2(vals)) for vals in vals_list]
    vals = img.new_tensor(vals_list).view(b, 1, 1, 1)
    out = torch.poisson(img * vals) / vals
    noise = out - img
    if cal_gray_noise:
        noise = noise * (1 - gray_noise) + noise_gray * gray_noise
    if not isinstance(scale, (float, int)):
        scale = scale.view(b, 1, 1, 1)
    return noise * scale


if __name__ == '__main__':

    img = torch.rand(1, 3, 192, 1152)

    test_two_rgb2gray_methods(img)

    test_expand_repeat(img)

    out = generate_poisson_noise_pt(img, gray_noise=1)
    print(out.shape)
```

**Comment by archernsy** [comment]
Thanks for your patient answer and attention！
